### PR TITLE
Add readme_cn.md

### PR DESCRIPTION
**Pull request by QilongZhang**
+ add README-CN.md
+ change `SOFA Ark` to `SOFAArk`
+ add deny classes/resources doc

### CODE REVIEW

**Comment by QilongZhang** [comment]
fix #31

**Comment by khotyn** [comment]
Awesome, should we add a link to README_CN on the top of README?

**Comment by QilongZhang** [comment]
@khotyn  refer to [this commit](https://github.com/alipay/sofa-ark/pull/31/commits/5793ffa57f0142de358086138886a7a17f9d8741)

**Comment by straybirdzls** [comment]
fix #30

**Pull request merged**
